[project]
name = "learn-langfuse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gradio>=6.9.0",
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "langfuse>=4.0.0",
    "openai>=2.29.0",
    "python-dotenv>=1.2.2",
]
